name: Csharp Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Install Playwright
      run: dotnet tool install --global Microsoft.Playwright.CSharp.Cli

    - name: Run tests
      run: dotnet playwright test
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports